### ISSUE TITLE
[Feature Request] Hacerlo portable a Linux

### ISSUE THREAD

**Issue by q2dg** [luisllamasbinaburo/Arduino-LiveSerial#1]
Hola.
Este es un espléndido programa pero es una lástima que solo pueda usarse en Windows.
¿Sería muy complicado portarlo a una tecnología multiplataforma, tal como Python, Node.js, Go o similar?
Gracias

**Comment by luisllamasbinaburo** [comment]
Es bastante difícil, sería hacer una App nueva de cero, esta está programada en C# + WPF. Sería más sencillo hacerlo multiplataforma con Mono, Xamarin, etc, Pero habría que buscar versiones compatibles de todas las librerías que emplea con estas plataformas (y algunas de ellas, no la tienen)
Puede que en el futuro.
